# This is a basic workflow that is manually triggered

name: build release
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      flavor:
        type: choice
        description: 'Debian/Ubuntu Version'
        options:
          - 'bullseye'
          - 'buster'
          - 'stretch'
        required: true
      bareos_tag:
        description: 'Bareos Version Tag'
        default: '21.1.2'
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/bareos-custom-build:${{ github.event.inputs.flavor }}
      options: --privileged --device /dev/fuse
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            cache
          key: "${{ github.event.inputs.flavor }}-build-cache-${{ github.event.inputs.bareos_tag }}"
          restore-keys: |
            "${{ github.event.inputs.flavor }}-build-cache-"
      - name: Run build script
        run: ./scripts/build.sh
        env:
          DEB_FLAVOR: "${{ github.event.inputs.flavor }}"
          BAREOS_TAG: "${{ github.event.inputs.bareos_tag }}"
      - name: Upload deb files
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./*.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.deb