name: build full release
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version_tag:
        description: 'Version Tag'
        default: '23.1.0'
        required: true
  create:
    tags:
      - '*'

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os-version: ["buster", "bullseye", "bookworm"]
        arch: ["amd64", "arm64"]
    container:
      image: "ghcr.io/${{ github.repository_owner }}/bacula-fork-custom-build:${{ matrix.os-version }}-${{ matrix.arch }}"
      options: --privileged --device /dev/fuse
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set env
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set env
        if: github.event.inputs.version_tag != ''
        run: echo "VERSION_TAG=${{ github.event.inputs.version_tag }}" >> $GITHUB_ENV
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            cache
          key: "${{ matrix.os-version }}-build-cache-${{ matrix.arch }}"
          restore-keys: |
            "${{ matrix.os-version }}-build-cache-${{ matrix.arch }}"
      - name: Run build script
        run: ./scripts/build.sh
        env:
          DEB_FLAVOR: "${{ matrix.os-version }}"
          DEB_HOST_ARCH: "${{ matrix.arch }}"
      - name: Upload deb files
        uses: actions/upload-artifact@v4
        with:
          name: "packages-${{ matrix.os-version }}-${{ matrix.arch }}"
          path: ./*.deb

  merge-artefacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: debian-packages
        uses: actions/upload-artifact/merge@v4

  add_release:
    name: Add package to release
    needs: merge-artefacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: merged-artifacts
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.deb

  add_repo:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      max-parallel: 1
      matrix:
        os-version: ["buster", "bullseye", "bookworm"]
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "packages-${{ matrix.os-version }}"
      - name: Display structure of downloaded files
        run: ls -R
      - name: Add ${{ matrix.os-version }} release
        uses: smeinecke/apt-repo-action@v2.1.4
        with:
          github_token: ${{ github.token }}
          repo_supported_arch: |
            amd64
            arm64
          repo_supported_version: |
            buster
            bullseye
            bookworm
          file: |
            *-${{ matrix.os-version }}*.deb
          file_target_version: ${{ matrix.os-version }}
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""